author = 'Oxalin'
country_code = 'GB'
description = "The Littlehampton area, including Arundel panel"
display_name = 'Littlehampton'
doc_files = [ 'Littlehampton.md' ]
factual = true
img_files = [ 'Littlehampton.bmp' ]
name = 'Littlehampton'
release_date = '2026-02-22'
rly_file = 'Littlehampton.rly'
ssn_files = []
ttb_files = [ 'Littlehampton_2026-02-25.ttb' ]
year = 2026
signal_position - "left"
version = '1.0.0'
